environment:

  matrix:
    - PYTHON: "C:\\Python27"
      ARCHITECTURE: "i386"
    - PYTHON: "C:\\Python27-x64" 
      ARCHITECTURE: "x86_64"
    - PYTHON: "C:\\Python35" 
      ARCHITECTURE: "i386"
    - PYTHON: "C:\\Python35-x64"
      ARCHITECTURE: "x86_64"

install:
  - ECHO "Filesystem root:"
  - ps: "ls \"C:/\""

  - ECHO "Installed SDKs:"
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""

  # install EnergyPlus
  - ECHO "Installing EnergyPlus"
  - ps: $env:ENERGYPLUS_VERSION = "8.5.0"
  - ps: $env:ENERGYPLUS_TAG = "v8.5.0"
  - ps: $env:ENERGYPLUS_SHA = "c87e61b44b"
  - ps: $env:ENERGYPLUS_INSTALL_VERSION = "8-5-0"
  - ps: $env:ENERGYPLUS_DOWNLOAD_BASE_URL = "https://github.com/NREL/EnergyPlus/releases/download/$env:ENERGYPLUS_TAG"
  - ps: $env:ENERGYPLUS_DOWNLOAD_FILENAME = "EnergyPlus-$env:ENERGYPLUS_VERSION-$env:ENERGYPLUS_SHA-Windows-$env:ARCHITECTURE.exe"
  - ps: $env:ENERGYPLUS_DOWNLOAD_URL = "$env:ENERGYPLUS_DOWNLOAD_BASE_URL/$env:ENERGYPLUS_DOWNLOAD_FILENAME"

  - ps: "curl $env:ENERGYPLUS_DOWNLOAD_URL -OutFile $env:TMP\\$env:ENERGYPLUS_DOWNLOAD_FILENAME"
  - ps: "& $env:TMP\\$env:ENERGYPLUS_DOWNLOAD_FILENAME /S | Out-Null"

  # Install Python (from the official .msi of http://python.org) and pip when
  # not already installed.
  - ps: if (-not(Test-Path($env:PYTHON))) { & appveyor\install.ps1 }

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  - "pip install --disable-pip-version-check --user --upgrade pip"
  - ps: echo $env:PYTHON
  - "%PYTHON%\\python.exe -m pip install pytest"
  # set the integration test environment variable
  - "SET EPPY_INTEGRATION=TRUE"
  # install eppy
  - "%PYTHON%\\python.exe setup.py install"

build: off

test_script:
  # Test command.
  - "%PYTHON%\\python.exe -m pytest eppy -v"
